name: CI Tests

on:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Begin linting
        uses: actions/checkout@v3
      - name: Use Node 14
        uses: actions/setup-node@v3
        with:
          node-version: "14"
          cache: "npm"
      - name: Install dependencies
        run: npm install
      - name: Run test
        run: npm test
      - name: Run coverage
        run: npm run cover
      - name: Publish to CodeClimate
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
          GIT_BRANCH: ${{github.head_ref}}
          GIT_COMMIT_SHA: ${{github.sha}}
